POST http://localhost:3001/api/persons
# POST https://full-stack-open-puhelinluettelo-backend.onrender.com/api/persons
content-type: application/json

{
    "name": "dude Im fairy",
    "number": "123456789"
}